### ISSUE TITLE
MoveBox_CaptureStudio_Avatar doesnt work!

### ISSUE THREAD

**Issue by nmeri12** [microsoft/MoveBox-for-Microsoft-Rocketbox#2]
Hello @margonzalezfranco,

I am trying to run the MoveBox_CaptureStudio project, cause my goal is to have the following scene : (Real time avatar)

![image](https://user-images.githubusercontent.com/25100317/104812814-27c16a80-5805-11eb-8904-fd5022ab5d0c.png)

BTW I use the Azure Kinect (as shown in the previous picture) and I have followed all the instructions that you mentioned but unfortunately it did not work. That's why It will be nice from you if you could help me. 
In addition to that, I am using a humanoid character, as well as, change the avatar but is always the same problems.

Here are some screen shoots from my project:con

![image](https://user-images.githubusercontent.com/25100317/104812970-496f2180-5806-11eb-963d-6a9e497536f4.png)

![image](https://user-images.githubusercontent.com/25100317/104812993-81766480-5806-11eb-86db-81409dd18562.png)

![image](https://user-images.githubusercontent.com/25100317/104813115-66582480-5807-11eb-91d5-beb7e713b466.png)

![image](https://user-images.githubusercontent.com/25100317/104813188-ce0e6f80-5807-11eb-8175-bf5ed1a3d30f.png)

Here I put tick in "optimize game object" cause if I don't choose this option it will not do the humanoid avatar 

I have also some other questions, that I wish you can respond to:

1- How can I fix this?

2- How can I create a scene without an avatar (character), just with a tracker (the red Tracker on the first picture)?

Thank you in advance
Best Regards
M.Nmeri

**Comment by margonzalezfranco** [comment]
Hi M. Nmeri,
Please send me an email at margon@microsoft.con and I can schedule some time to help tou

Dr. Mar Gonzalez Franco
margon@microsoft.com
http://research.microsoft.com/people/margon
Microsoft Research, One Microsoft Way, Redmond, WA 98052, USA
Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by margonzalezfranco** [comment]
Summary of the solution: do not change anything on the demo project and make sure the azure kinect steps have been followed. In particular do not change the attributes of the type of avatar (it does not need to be a humanoid, leave it as a generic).
