### ISSUE TITLE
how to remove the tracker

### ISSUE THREAD

**Issue by ankou104** [microsoft/MoveBox-for-Microsoft-Rocketbox#3]
Hi @margonzalezfranco ,

I have two issues and I would be happy if someone could help me.

1. I would like to remove the tracker from the scene, but I cannot find a way to do it, because when I tried to remove it and add the movebox script to the avatar male 04 it doesn't work. It feels like the avatar is a child of the tracker because when I move or rotate the tracker the avatar does the same. Is there a way to remove the tracker? If yes, how? By changing something in the code? If yes, in which script?

2. When I press play, the tracker and the avatar change their global position and there is a rotation of 180 degrees (meaning taht before I press play the avatar looks on the opposite direction of the camera, however when I press play the avatar rotates by its self to the right position, looking the camera). How can I have a scene that the avatar is facing the camera without changing its position and rotation before and after pressing play?

Thank you in advance
Best Regards
Andrea

**Comment by margonzalezfranco** [comment]
Hi Andrea,
Sounds like the best would be to look at this together.
Send me an email and let’s have a working session on this. We can report back to the thread what we find.
margon@microsoft.com

Dr. Mar Gonzalez Franco
margon@microsoft.com
http://research.microsoft.com/people/margon
Microsoft Research, One Microsoft Way, Redmond, WA 98052, USA
Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by margonzalezfranco** [comment]
Hi Andrea, 
Not sure if you are talking about the Capture Studio or the IK project.

In the Capture Studio
If you use the latest commit it should allow you to turn on/off the draw skeleton and so turn off the visual part of the tracker.

In the IK project
You could unselect the renderer box of the tracker. And the whole logic will still work
